name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn aqui"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "journey-us-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "journey-us-east-1-terraform-lock"
  